### PR TITLE
Fix `PropTypes.date`: it isn't a valid PropType, use `instanceOf(Date)`

### PR DESCRIPTION
**Pull request by orioltf**
`PropTypes.date` doesn't seem to be a valid PropType: https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes

We can however use `PropTypes.instanceOf(Date)` instead 😄

### CODE REVIEW

**Comment by orioltf** [comment]
Hmm… I wonder anyway whether this change makes sense, cause the provided data will anyway be a String… 🤔

**Comment by vovanmix** [comment]
Hi @orioltf!
Yeah I think it's better to use string!

**Comment by orioltf** [comment]
Great!  I'll update the PR and remove the whole logic about dates 😊

**Comment by orioltf** [comment]
There you go: type strings get `PropType.string` now 😄

**Comment by orioltf** [comment]
There you go: type strings get `PropType.string` now 😄

**Comment by vovanmix** [comment]
merged, thank you!

**Pull request merged**
